### ISSUE TITLE
Feature request: No barrel roll option

### ISSUE THREAD

**Issue by boredompwndu** [c-basse/c-basse#1]
### Expected Behavior 

Alongside the ability to barrel roll "fwd" "mid" "bwd" and "all", I would like a Barrel roll "off" option in which no barrel rolls are shown.

**Comment by c-basse** [comment]
Thanks for the feedback. That option set for barrel roll you are talking about is actually for slide directions, so, for example, it also impacts talon rolls and decloaks which I don't want to be disabled by selecting off. I'll look into adding a new option for selecting which reposition actions to enable: all | roll only | boost only | none.

My biggest hesitation is need an intuitive icon that represents "Actions"...

**Comment by c-basse** [comment]
Added toggle switches for enable/disable of roll, boost, and slam. The original option for slide has a new icon that is double sided vertical arrow instead of the original barrel roll icon.
